server:
  port: 8085
  servlet:
    jsp:
      init-parameters:
        development: true

logging:
  level:
    root: info
    com:
      example:
        fandomTest: trace
    org:
      hibernate: info

spring:
  # DB source
  datasource:
    url: jdbc:mariadb://localhost:3306/newjeans
    username: root
    password: mariadb
  servlet:
    multipart:
      location:
        E:/Fandom/fandomTest/src/main/resources/static/img/userImg/
      max-file-size:
        10MB
      max-request-size:
        50MB

  # JPA config
  jpa:
    properties:
      hibernate:
        format_sql: true
        direct: org.hibernate.dialect.MariaDB106Dialect
    show-sql: true
    hibernate:
      database: mysql
      generate-ddl: true
      ddl-auto: update
      naming:
        physical-strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  PhysicalNamingStrategyStandardImpl:# JSP
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

file:
  dir:
    E:/Fandom/fandomTest/src/main/resources/static/img/userImg/